version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: prod
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: 1
      S6_VERBOSITY: 2 # default is 1, goes from 1-5
      S6_KEEP_ENV: 0 # default is 0, keeps the environment variables
      S6_STAGE2_HOOK: /etc/s6-hook/feature-toggle
      FEATURE_MIGRATIONS_ENABLED: "false"
      FEATURE_SCHEDULER_ENABLED: "false"
      FEATURE_SECURITY_CHECK_ENABLED: "true"
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7.43
#    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app'
      # You can use whatever password you like
      MYSQL_PASSWORD: '!ChangeMe!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
    my-db:
