version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    ports:
      - "8085:80"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: 1
      S6_VERBOSITY: 5 # default is 1, goes from 1-5
      S6_KEEP_ENV: 1 # default is 0, keeps the environment variables
    volumes:
      - ./app:/var/www/html

  serversideup:
    build:
      context: .
      dockerfile: docker/serversideup/Dockerfile
      target: dev
    ports:
      - "8081:80"
    environment:
      APP_ENV: "dev"
      S6_VERBOSITY: "4" # default is 1, goes from 1-5
    volumes:
      - ./app:/var/www/html/:cached