#!/command/with-contenv sh

# Check if APP_DEBUG is set and its value is 1
if [ -z "$APP_DEBUG" ] || [ "$APP_DEBUG" != "1" ]; then
    echo "check-dependencies: info: APP_DEBUG is not set or is not 1. Exiting..."
    exit 0
fi

# Continue with the rest of your script or command here
# Check if the composer binary exists
if command -v composer >/dev/null 2>&1; then
    # Composer is installed, run composer install
    echo "check-dependencies: info: Composer found. Checking dependencies."
    cd /var/www/html
    composer check-platform-reqs
else
    # Composer not found
    echo "check-dependencies: info: Composer not found. Please install Composer before running this script."
    exit 0
fi
exit 0
