#!/usr/bin/env sh

install -d -m 0755 -o www-data -g www-data /tmp/nginx/cache;
install -d -m 0755 -o www-data -g www-data /var/lib/nginx/tmp/client_body;
echo "init-nginx: info: everything prepared to run nginx"
