#!/usr/bin/env sh

echo "init-security-check: info: running $0"

# Check if the composer binary exists
if command -v composer >/dev/null 2>&1; then
    # Composer is installed, run composer install
    echo "init-security-check: info: Composer found. Installing security checker."
    composer global require enlightn/security-checker
    composer global update enlightn/security-checker
    echo "init-security-check: info: Run security checker."
    /root/.composer/vendor/bin/security-checker security:check composer.lock
else
    # Composer not found
    echo "init-security-check: info: Composer not found. Please install Composer before running this script."
    exit 0
fi