#!/command/with-contenv sh

if v=`printcontenv S6_VERBOSITY` && eltest "$v" =~ '^[[:digit:]]+$' ; then : ; else
  v=2
fi

if migration=`printcontenv APP_RUN_MIGRATION` && eltest "$migration" =~ '^yes$' ; then : ; else
  if test $v -ge 2 ; then
    echo "init-migrations: info: no migration set." 1>&2
  fi
  exit 0
fi

cd /var/www/html || exit 1

if test $v -ge 2 ; then
  echo "init-migrations: info: starting migrations" 1>&2
fi
php bin/console doctrine:migrations:migrate --no-interaction
php bin/console doctrine:migrations:status

if test $v -ge 2 ; then
  echo "init-migrations: info: migrations executed" 1>&2
fi
