#!/command/with-contenv sh

if v=`printcontenv S6_VERBOSITY` && eltest "$v" =~ '^[[:digit:]]+$' ; then : ; else
  v=2
fi

if migration=`printcontenv APP_RUN_MIGRATION` && eltest "$migration" =~ '^Version[[:digit:]]{14}$' ; then : ; else
  if test $v -ge 2 ; then
    echo "migrations-migrate: info: no migration set. $migration" 1>&2
  fi
  exit 0
fi

cd /var/www/html

if test -f "/var/www/html/migrations/$migration.php" ; then
  if test $v -ge 2 ; then
      echo "migrations-migrate: info: migration file exists. /var/www/html/migrations/$migration.php" 1>&2
  fi
else
  if test $v -ge 1 ; then
      echo "migrations-migrate: warning: migration file does not exist. /var/www/html/migrations/$migration.php" 1>&2
      echo "migrations-migrate: warning: exit 1" 1>&2
  fi
  exit 1
fi


if test $v -ge 2 ; then
  echo "migrations-migrate: info: starting migration DoctrineMigrations\\$migration.php" 1>&2
fi
php bin/console doctrine:migrations:migrate DoctrineMigrations\\$migration -n > /dev/stderr
php bin/console doctrine:migrations:status > /dev/stderr

if test $v -ge 2 ; then
  echo "migrations-migrate: info: migrations executed" 1>&2
fi
