#!/command/with-contenv sh

if v=`printcontenv S6_VERBOSITY` && eltest "$v" =~ '^[[:digit:]]+$' ; then : ; else
  v=2
fi

cd /var/www/html
php bin/console doctrine:migrations:status > /dev/stderr

if test $v -ge 2 ; then
  echo "migrations-status: info: running $0" 1>&2
fi
